- name: Set sysctl performance variables
  become: true
  become_user: root
  shell:
    # Note: this overwrite the file, if you want to append replace EOM with EOF
    cmd: |
      bash -c 'cat >> /etc/sysctl.conf <<- EOM
      # set minimum, default, and maximum tcp buffer sizes (10k, 87.38k (linux default), 12M resp)
      net.ipv4.tcp_rmem=10240 87380 12582912
      net.ipv4.tcp_wmem=10240 87380 12582912
      # Enable TCP westwood for kernels greater than or equal to 2.6.13
      net.ipv4.tcp_congestion_control=westwood
      net.ipv4.tcp_fastopen=3
      net.ipv4.tcp_timestamps=0
      net.ipv4.tcp_sack=1
      net.ipv4.tcp_low_latency=1
      # Enable fast recycling TIME-WAIT sockets
      # net.ipv4.tcp_tw_recycle = 1 this is in solana tuner, but fails, changing to below, see - https://djangocas.dev/blog/troubleshooting-tcp_tw_recycle-no-such-file-or-directory/
      net.ipv4.tcp_tw_reuse = 1
      # dont cache ssthresh from previous connection
      net.ipv4.tcp_no_metrics_save = 1
      net.ipv4.tcp_moderate_rcvbuf = 1

      # kernel Tunes
      kernel.timer_migration=0
      kernel.hung_task_timeout_secs=30
      # A suggested value for pid_max is 1024 * <# of cpu cores/threads in system>
      kernel.pid_max=49152

      # vm.tuning
      vm.swappiness=1
      vm.max_map_count=1000000
      vm.stat_interval=10
      vm.dirty_ratio=40
      vm.dirty_background_ratio=10
      vm.min_free_kbytes = 3000000
      vm.dirty_expire_centisecs=36000
      vm.dirty_writeback_centisecs=3000
      vm.dirtytime_expire_seconds=43200

      fs.nr_open = 1000000

      # solana systuner
      net.core.rmem_max=134217728
      net.core.rmem_default=134217728
      net.core.wmem_max=134217728
      net.core.wmem_default=134217728
      EOM'
  args:
    executable: /bin/bash

- name: Reload sysctl
  become: true
  become_user: root
  shell: sysctl -p

- name: Set performance governor
  become: true
  become_user: root
  shell: |
    echo 'GOVERNOR="performance"' | tee /etc/default/cpufrequtils
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu8/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu9/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu10/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu11/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu12/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu13/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu14/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu15/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu16/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu17/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu18/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu19/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu20/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu21/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu22/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu23/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu24/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu25/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu26/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu27/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu28/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu29/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu30/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu31/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu32/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu33/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu34/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu35/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu36/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu37/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu38/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu39/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu40/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu41/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu42/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu43/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu44/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu45/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu46/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu47/cpufreq/scaling_governor
  args:
    executable: /bin/bash

- name: Set performance governor bare metal
  become: true
  become_user: root
  shell: |
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu8/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu9/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu10/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu11/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu12/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu13/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu14/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu15/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu16/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu17/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu18/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu19/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu20/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu21/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu22/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu23/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu24/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu25/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu26/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu27/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu28/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu29/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu30/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu31/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu32/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu33/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu34/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu35/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu36/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu37/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu38/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu39/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu40/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu41/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu42/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu43/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu44/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu45/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu46/cpufreq/scaling_governor
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu47/cpufreq/scaling_governor
  args:
    executable: /bin/bash
  ignore_errors: True
